# Generated by Django 3.1.7 on 2021-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0002_auto_20210321_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
