# Generated by Django 3.1.7 on 2021-03-23 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0006_auto_20210321_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_date', models.DateTimeField()),
                ('batch_id', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Account with Email ID already exists'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(error_messages={'unique': 'Username Already Taken'}, max_length=10, unique=True),
        ),
    ]
