# Generated by Django 3.1.7 on 2021-03-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0011_auto_20210323_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
