# Generated by Django 3.1.7 on 2021-03-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0013_auto_20210324_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cluster_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expensemanagerapp.cluster'),
        ),
    ]
