# Generated by Django 3.1.7 on 2021-03-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0014_auto_20210324_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cluster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensemanagerapp.cluster'),
        ),
    ]
