# Generated by Django 3.1.7 on 2021-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0015_auto_20210324_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='cluster_id',
            new_name='cluster',
        ),
    ]
