# Generated by Django 3.1.7 on 2021-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0016_auto_20210324_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
    ]
