# Generated by Django 3.1.7 on 2021-03-25 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0018_cluster_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='last_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 18, 57, 34, 481699)),
        ),
    ]
