# Generated by Django 3.1.7 on 2021-03-25 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagerapp', '0020_auto_20210325_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
